### PR TITLE
fix: use publiccode.yml's url when cloning the repo locally

### LINKED ISSUE #264: Vitality for metarepos is off
Vitality of software using metarepos is wrong, because it's being calculated against the metarepo itself

eg. https://developers.italia.it/it/software/italia-software-freepbx-1b386f 
image

(uses https://github.com/italia-software/FreePBX instead of https://github.com/FreePBX/devtools)

### PR DESCRIPTION
**Pull request by bfabio**
Use the URL in publiccode.yml when cloning the repo locally, so the
vitality of software using metarepos is calculated against the actual software
repository instead of the metarepo itself.

Fix #264.

### CODE REVIEW

File: crawler/crawler/cloneRepository.go [hunk 1]
```diff
@@ -33,17 +33,13 @@ func CloneRepository(domain Domain, hostname, name, gitURL, gitBranch, index str
 		if err != nil {
 			return errors.New(fmt.Sprintf("cannot git pull the repository: %s: %s", err.Error(), out))
 		}
-		// Command is: git reset --hard origin/<branch_name>
-		out, err = exec.Command("git", "-C", path, "reset", "--hard", "origin/"+gitBranch).CombinedOutput() // nolint: gas
```
Comment (LorenzoS92) [inline crawler/crawler/cloneRepository.go:37]: Is wanted that we removed git reset --hard?

**Review by LorenzoS92 — APPROVED** [review]

File: crawler/crawler/cloneRepository.go (hunk 1 above)
Comment (bfabio) [reply crawler/crawler/cloneRepository.go:37]: Uhm, actually we want it in. I didn't notice we are `git fetch`ing instead of `git pull`ing a few lines above (we'll probably take care of that for #249). Thanks!

Let's `reset` to `origin/HEAD`.

**Review by LorenzoS92 — APPROVED** [review]
Perfect!
No unit tests are affected, right?
If so, ok to me!
